---
# tasks file for dev-tools

  - name: Install Development Tools Group
    become: true
    yum: name="@Development tools" state=latest

  - name: Install additional dev tools
    become: true
    yum: name={{ dev_tools }} state=latest

  - name: Install DB Development Packages
    become: true
    yum: name={{ db_dev_packages }} state=latest

  - name: Install Python Development Packages
    become: true
    yum: name={{ py_dev_packages }} state=latest

  - name: Install Compression Development Packages
    become: true
    yum: name={{ compression_dev_packages }} state=latest

  - name: Install Graphics Development Packages
    become: true
    yum: name={{ graphics_dev_packages }} state=latest

  - name: Install Security Development Packages
    become: true
    yum: name={{ security_dev_packages }} state=latest

  - name: Install Misc Development Packages
    become: true
    yum: name={{ misc_dev_packages }} state=latest