---
# tasks file for slack
  - name: Check if slack is already installed
    yum:
      list: slack
    register: slack_packages

  - name: Set fact 
    set_fact: 
      slack_exists: slack_packages.results | selectattr("yumstate", "match", "installed") | list | length > 0

  - name: Set fact 
    set_fact: 
      slack_installed_ver: "{{ slack_packages.results 
        | selectattr('yumstate', 'match', 'installed')
        | map(attribute='version') | list | first | default('0.0.0') }}"
    when: slack_exists

  - name: Print slack_installed_ver fact
    debug:
      msg: "Slack version is {{ slack_installed_ver }}"
    when: debug_all or debug_slack

  - name: Download slack RPM
    become: true
    get_url: url={{ slack_uri }} dest={{ HOME }} mode=0775 remote_src=yes
    when: not slack_exists or slack_installed_ver != slack_version

  - name: Install Slack Dependencies
    become: true
    yum: name={{ item }} state=latest
    with_items: '{{ slack_packages }}'
    when: not slack_exists

  - name: Install Slack
    become: true
    yum: name='{{ HOME }}/{{ slack_rpm }}' state=present
    when: not slack_exists or slack_installed_ver != slack_version
